name: Build and Deploy

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install Dependencies
        run: yarn install
      - name: Build Tailwind CSS
        run: yarn build
      - uses: actions/setup-go@v2
        with:
          go-version: '1.16'
          check-latest: true
      - name: Install Go Dependencies
        run: go mod download
      - name: Verify Go Dependencies
        run: go mod verify
      - name: Build Go Server
        run: go build -v -o /carp
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and Push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: user/app:latest
